when@dev:
    _errors:
        resource: '@FrameworkBundle/Resources/config/routing/errors.xml'
        prefix: /_error

    _video:
        resource: '.../public/index.php'
        prefix: /index.php
